# Generated by Django 3.2.9 on 2021-11-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_pj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qsenews',
            name='news_url',
            field=models.TextField(blank=True),
        ),
    ]
