# Generated by Django 3.2.9 on 2021-12-26 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parser_pj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(blank=True, max_length=600)),
                ('company_name', models.CharField(blank=True, max_length=600)),
                ('buy_volume', models.IntegerField(blank=True, null=True)),
                ('sell_volume', models.IntegerField(blank=True, null=True)),
                ('report_data', models.DateTimeField(blank=True, null=True)),
                ('creat', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
