# Generated by Django 3.2.9 on 2021-11-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_pj', '0002_qsenews_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qsenews',
            name='news_download_attachment_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
