# Generated by Django 3.2.9 on 2021-12-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_pj', '0003_alter_qsenews_news_download_attachment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='qsenews',
            name='news_body_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qsenews',
            name='news_title_ar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
