# Generated by Django 3.2.9 on 2021-12-02 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parser_pj', '0004_auto_20211201_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='QSENewsAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(blank=True, max_length=600)),
                ('news_title', models.TextField(blank=True)),
                ('news_body', models.TextField(blank=True)),
                ('news_date', models.DateTimeField(blank=True, null=True)),
                ('news_download_attachment_url', models.TextField(blank=True, null=True)),
                ('news_url', models.TextField(blank=True)),
                ('creat', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='qsenews',
            name='news_body_ar',
        ),
        migrations.RemoveField(
            model_name='qsenews',
            name='news_title_ar',
        ),
    ]
